### ISSUE TITLE
Meet an exception when running rust examples with buid.sh

### ISSUE THREAD

**Issue by lum1n0us** [bytecodealliance/wasi-nn#101]
I am using a debian bookworm image. Installed openvino_2024.1.0.15008(using [archive](https://docs.openvino.ai/2024/get-started/install-openvino/install-openvino-archive-linux.html)). Installed wasmtime-v21.0.1 [release](https://github.com/bytecodealliance/wasmtime/releases/download/v21.0.1/wasmtime-v21.0.1-x86_64-linux.tar.xz). Cloned latest wasi-nn repo.

Meet below exception

``` bash
$ pwd
/workspace/wasi-nn
$ ./build.sh rust

...
Read graph XML, first 50 characters: <?xml version="1.0" ?>
<net name="mobilenet_v2_1.0
Read graph weights, size in bytes: 13956476
thread 'main' panicked at crates/wasi-nn/src/witx.rs:45:49:
not implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

---

I noticed that [CI](https://github.com/bytecodealliance/wasi-nn/blob/main/.github/workflows/main.yaml) uses a compiled-from-source building, So switched to a new wasmtime build-from-source

``` bash
$ git clone https://github.com/bytecodealliance/wasmtime --recursive wasmtime
$ cd wasmtime
$ git checkout --track origin/release-21.0.0
$ OPENVINO_INSTALL_DIR=/opt/intel/openvino cargo build -p wasmtime-cli --features wasi-nn 
```

but this time the exception is still there:

```
Read graph XML, first 50 characters: <?xml version="1.0" ?>
<net name="mobilenet_v2_1.0
Read graph weights, size in bytes: 13956476
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/openvino-sys-0.6.0/src/generated/functions.rs:3:1:
`openvino_c` function not loaded: `ie_core_create
```

Please guide me through. Thanks

**Comment by abrown** [comment]
@lum1n0us, what is going on here is that OpenVINO has switched to a new API and the Rust bindings that Wasmtime uses need to be updated to the newly-released v0.7.1 of the `openvino` crate. Actually @rahulchaphalkar is working on that at the moment; maybe he can CC you once that PR is ready.
